Eventbrite-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/index'
  get 'static_pages/secret'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "events#index", :id => '1'
  resources :events
  resources :users, only: [:show, :edit, :update]
end

Eventbrite-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Eventbrite-master/app/models/event.rb
class Event < ApplicationRecord
#  after_create :new_participation

#  def new_participation
#    EventMailer.new_participation(self).deliver_now
#  end

  validates :start_date,
    presence: true
    validate :in_the_past?
  validates :duration,
    presence: true,
    numericality: { greater_than_or_equal_to: 5 }
    validate :multiple_of_5?
  validates :title,
    presence: true,
    length: { in: 5..140 }
  validates :description,
    presence: true,
    length: { in: 20..1000 }
  validates :price,
    presence: true,
    length: { in: 1..1000 }
  validates :location,
    presence: true

  has_many :participations
  has_many :users, through: :participations
  belongs_to :user

  private

  def multiple_of_5?
    return duration unless duration % 5 != 0 || duration.negative?
    errors.add(
      :duration,
      'The duration must end by 0 ou 5 and be a positive number.'
    )
  end

  def in_the_past?
    return start_date unless start_date < Time.now
    errors.add(:start_date, 'The start date cannot be in the past!')
  end
end

Eventbrite-master/app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

Eventbrite-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :participations
  has_many :events, through: :participations

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

Eventbrite-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Eventbrite-master/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def show
    @id = params[:id]
    @event = Event.all.find(params[:id])
  end

  def new
    @event = Event.new
  end
end

Eventbrite-master/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

Eventbrite-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

Eventbrite-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Eventbrite-master/app/helpers/events_helper.rb
module EventsHelper
end

Eventbrite-master/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Eventbrite-master/app/helpers/users_helper.rb
module UsersHelper
end

Eventbrite-master/app/views/events/index.html.erb
<html>
  <body>
    <div class="container justify-content-center text-center">
      <div class="col-lg-12">
        <h1>Bienvenue sur la page des événements</h1>
        <button class=" btn btn-dark btn-lg" role="button" aria-pressed="true"><%=link_to 'Nouvel événement ?', new_event_path %> </button>
          <% Event.all.each do |event| %>
          <div class="card">
            <div class="card-body">
                <h3 class="card-title"><%=link_to event.title, event_path(event.id) %> </h3>
                <p class="card-text"><%= event.description %></p>	    	
              </div>	
            </div>
          <% end %>
      </div>
    </div>
  </body>
</html>

Eventbrite-master/app/views/events/show.html.erb
<html>
  <body>
    <div class="container justify-content-center text-center">
      <div class="col-lg-12">
        <h1>Bienvenue sur la page de l'événement <%= @event.title %> </h1>
        <div class="card">
		  <div class="card-body">
		  	<h3 class="card-title"><%= @event.title %></h3>
		  	  <p class="card-text">
                <%= @event.description %>
                <%= @event.price %><br>
                <%= @event.location %><br>
                <%= @event.start_date %><br>
              </p>
		  	  <blockquote class="blockquote mb-0">
		  		<footer class="blockquote-footer text-right">
                  <p>Durée en minutes : <%= @event.duration %><br></p>
                </footer></blockquote>
		  </div>
    	</div>
      </div>
    </div>
  </body>
</html>

Eventbrite-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Eventbrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= events_path %>">Accueil <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Créer un événement</a>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_path(current_user) %>">Profil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= destroy_user_session_path %>">Se déconnecter</a>
          </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">S'inscrire</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_path(current_user) %>">Se connecter</a>
          </li>
        <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

Eventbrite-master/app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

Eventbrite-master/app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

Eventbrite-master/app/views/users/show.html.erb
<html>
  <body>
    <div class="container justify-content-center text-center">
      <div class="col-lg-12">
        <h1>Bienvenue sur la page de l'utilisateur <%= current_user.email %> </h1>
	    <% @user.events.each do |event| %>
		  <div class="card">
			<div class="card-body">
			  <h3 class="card-title"><%=link_to event.title, event_path(event.id) %> </h3>			          	
			</div>	
	      </div> 
	    <% end %>
        <p>
          <%= link_to 'Changer ses informations de profil', edit_user_registration_path %>
        </p>
      </div>
    </div>
  </body>
</html>